### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by guymcswain** [vesteraas/node-pitft-touch#6]
I tried your node-pitft and the examples worked great! 👍   But I need a touchscreen also.  I'm using the Adafruit 2.8" capacitive touch.  Any help would be greatly appreciated.  I'm on RPi3b+ with /etc/os-release:

> PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="9"
> VERSION="9 (stretch)"
> ID=raspbian
> ID_LIKE=debian

```
git clone https://github.com/vesteraas/node-pitft-touch.git
cd node-pitft-touch
npm install
```
 

> \> pitft-touch@0.0.6 install /home/pi/node-pitft-touch
> \> node-gyp rebuild
> 
> make: Entering directory '/home/pi/node-pitft-touch/build'
>   CXX(target) Release/obj.target/ts/src/touchscreen.o
> In file included from ../node_modules/nan/nan_new.h:189:0,
>                  from ../node_modules/nan/nan.h:222,
>                  from ../src/touchscreen.cc:6:
> ../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
> ../node_modules/nan/nan_implementation_12_inl.h:340:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
>    return v8::StringObject::New(value).As<v8::StringObject>();
>                                      ^
> In file included from /home/pi/.node-gyp/10.14.0/include/node/v8.h:26:0,
>                  from ../src/touchscreen.cc:4:
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:5053:37: note: declared here
>                  static Local<Value> New(Local<String> value));
>                                      ^
> /home/pi/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> In file included from ../src/touchscreen.cc:6:0:
> ../node_modules/nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
> ../node_modules/nan/nan.h:1066:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
>        v8::Local<v8::String> string = from->ToString();
>                                                      ^
> In file included from ../src/touchscreen.cc:4:0:
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:10040:15: note: declared here
>  Local<String> Value::ToString() const {
>                ^~~~~
> In file included from ../src/touchscreen.cc:6:0:
> ../node_modules/nan/nan.h:1080:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
>          length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
>                                                                           ^
> In file included from /home/pi/.node-gyp/10.14.0/include/node/v8.h:26:0,
>                  from ../src/touchscreen.cc:4:
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:2659:21: note: declared here
>                  int WriteUtf8(char* buffer, int length = -1,
>                      ^
> /home/pi/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> ../src/touchscreen.cc: In function ‘void AsyncAfter(uv_work_t*)’:
> ../src/touchscreen.cc:91:18: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
>          TryCatch try_catch;
>                   ^~~~~~~~~
> In file included from ../src/touchscreen.cc:4:0:
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:8536:12: note: candidate: v8::TryCatch::TryCatch(v8::Isolate*)
>    explicit TryCatch(Isolate* isolate);
>             ^~~~~~~~
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:8536:12: note:   candidate expects 1 argument, 0 provided
> ../src/touchscreen.cc:93:81: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>          touchInfo->callback->Call(Nan::GetCurrentContext()->Global(), argc, argv);
>                                                                                  ^
> In file included from ../src/touchscreen.cc:6:0:
> ../node_modules/nan/nan.h:1633:3: note: declared here
>    Call(v8::Local<v8::Object> target
>    ^~~~
> ../src/touchscreen.cc:96:37: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
>              FatalException(try_catch);
>                                      ^
> In file included from ../src/touchscreen.cc:5:0:
> /home/pi/.node-gyp/10.14.0/include/node/node.h:429:29: note: declared here
>                  inline void FatalException(const v8::TryCatch& try_catch) {
>                              ^
> /home/pi/.node-gyp/10.14.0/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> ../src/touchscreen.cc:118:27: error: no matching function for call to ‘v8::TryCatch::TryCatch()’
>                   TryCatch try_catch;
>                            ^~~~~~~~~
> In file included from ../src/touchscreen.cc:4:0:
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:8536:12: note: candidate: v8::TryCatch::TryCatch(v8::Isolate*)
>    explicit TryCatch(Isolate* isolate);
>             ^~~~~~~~
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:8536:12: note:   candidate expects 1 argument, 0 provided
> ../src/touchscreen.cc:120:90: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
>                   touchInfo->callback->Call(Nan::GetCurrentContext()->Global(), argc, argv);
>                                                                                           ^
> In file included from ../src/touchscreen.cc:6:0:
> ../node_modules/nan/nan.h:1633:3: note: declared here
>    Call(v8::Local<v8::Object> target
>    ^~~~
> ../src/touchscreen.cc:121:104: warning: ‘bool v8::Value::BooleanValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
>                   touchInfo->stop = touch->Get(Nan::New<String>("stop").ToLocalChecked())->BooleanValue();
>                                                                                                         ^
> In file included from /home/pi/.node-gyp/10.14.0/include/node/v8.h:26:0,
>                  from ../src/touchscreen.cc:4:
> /home/pi/.node-gyp/10.14.0/include/node/v8.h:2474:43: note: declared here
>    V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
>                                            ^
> /home/pi/.node-gyp/10.14.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
>    declarator __attribute__((deprecated(message)))
>    ^~~~~~~~~~
> ../src/touchscreen.cc:124:46: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
>                       FatalException(try_catch);
>                                               ^
> In file included from ../src/touchscreen.cc:5:0:
> /home/pi/.node-gyp/10.14.0/include/node/node.h:429:29: note: declared here
>                  inline void FatalException(const v8::TryCatch& try_catch) {
>                              ^
> /home/pi/.node-gyp/10.14.0/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
>      __attribute__((deprecated(message))) declarator
>                                           ^~~~~~~~~~
> ts.target.mk:99: recipe for target 'Release/obj.target/ts/src/touchscreen.o' failed
> make: *** [Release/obj.target/ts/src/touchscreen.o] Error 1
> make: Leaving directory '/home/pi/node-pitft-touch/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> gyp ERR! System Linux 4.14.52-v7+
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/pi/node-pitft-touch
> gyp ERR! node -v v10.14.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! pitft-touch@0.0.6 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the pitft-touch@0.0.6 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/pi/.npm/_logs/2018-12-04T18_04_26_954Z-debug.log

**Comment by guymcswain** [comment]
Replacing `TryCatch try_catch;` with `Nan::TryCatch try_catch;` resolves the build errors.  However, running the *buttons.js* example results in only the "3" button working properly.  Some buttons don't work at all and others work intermittently but all display the number 3 to the console.

**Comment by guymcswain** [comment]
The output from running *test.js* seems reasonable.  So maybe there is a problem within *buttons.js*.

Thanks for sharing this library!  I'll be happy to send you a PR if you like.

**Comment by vesteraas** [comment]
Thank you for your interest in my libraries, and for your research!  I've struggled a couple of hours now trying to set up a Raspberry Pi with a PiTFT display to test this.  Things have changed a lot since the last time I worked with this.  I've just found an issue with my pitft-library, which may be the cause of your problem regarding the button.js example program.  It has to do with fb.size() returning the wrong width and height.

I used this guide at Adafruit for setting up my display: https://learn.adafruit.com/running-opengl-based-games-and-emulators-on-adafruit-pitft-displays/pitft-setup could you please share your setup?

**Comment by guymcswain** [comment]
I'm using this Adafruit setup guide: [https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install-2](https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi/easy-install-2)
I did not enable the FBCP.

**Comment by guymcswain** [comment]
I came across [this informative article](http://ozzmaker.com/programming-a-touchscreen-on-the-raspberry-pi/) that could help you improve the touch output events.  He describes the flow of events as follows:

> 1 Event type is Key & Event code is TOUCH(330) & Event value is 1 = Touch Starting
> 2 Event type is Absolute & Event code is X(0) & Event value is 2163 = Raw X
> 3 Event type is Absolute & Event code is X(1) & Event value is 2193 = Raw Y
> 4 Event type is Absolute & Event code is X(24) & Event value is 13806 = Pressure
> 5 Event type is Sync = Start of New Event
> 6 Event type is Absolute & Event code is X(0) & Event value is 2178 = Raw X
> 7 Event type is Absolute & Event code is X(1) & Event value is 2204 = Raw Y
> 8 Event type is Absolute & Event code is X(24) & Event value is 13637 = Pressure
> 9 Event type is Sync = Start of New Event
> 10 Event type is Absolute & Event code is X(0) & Event value is 2143 = Raw X
> 11 Event type is Absolute & Event code is X(1) & Event value is 2249 = Raw Y
> 12 Event type is Absolute & Event code is X(24) & Event value is 13405 = Pressure
> 13 Event type is Sync = Start of New Event
> 14 Event type is Key & Event code is TOUCH(330) & Event value is 0 = Touch Finished


> Line 1 indicates touch is starting.
> Lines 3,4,5 are the raw values for X, Y and Pressure values
> Line 5 indicates the start of a new event.
> Line 6 to 12 are three more events. This is me sliding my finger across the touchscreen.
> Lines 13,14 & 15 is a new event indicating that touch has finished.
> 
I think if you just modify your library to invoke the callback only after `EV_SYN` then the stale coordinates will be removed.  If you also track the state of touch during `BTN_TOUCH` by adding a new property to `touchInfo` object, then you should get events generated when the finger is sliding across the screen (which I also need 😄 ).
